version: "3.8"

services:
  mongodb:
    container_name: mongo-service
    image: mongo:6.0.13
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 300M

  redis:
    container_name: redis-service
    image: redis:7.0.5-alpine
    restart: unless-stopped
    expose:
      - 6379
    deploy:
      resources:
        limits:
          memory: 100M

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "31100:8080"
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 250M

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 250M

volumes:
  mongo-data:

